### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#1]
All docs require updating.

**Comment by lloan** [comment]
We might benefit from breaking this in to multiple issues, one for each documentation item that needs updating. The priority, in comparison to the components is much lower, but these would be great issues for new contributors to tackle.

**Comment by paulcummings01** [comment]
I'm willing to work on this. What types of documentation updates are needed?

**Comment by rvilleda851** [comment]
how would I get started

**Comment by lloan** [comment]
@rvilleda851 Let me get some input from @tonynguyen111997 @johnathantng and @VelazquezLuis - guys, can we figure out how to break up documentation? As in figure out which pages under docs need to be updated? Thanks!

**Comment by rvilleda851** [comment]
@lloan  ok

**Comment by lloan** [comment]
Closing because this application will be rebuilt in the near future. That application will require a team member to document as the team builds.
