### ISSUE TITLE
Component: Mission

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#10]
This component is pretty simple. For v1, you can use 2 images for the right side. 1 layer is the actual image and the second layer is the cutout for IE. These can be found here: `static/images/mobile/ie-background` and `static/images/mobile/ie-cutout`

To get the padding required on both sides, Calcite uses 24 columns. You'll want your content to be within 20 columns and you can use `pre-2` to move your content 2 columns from the left. Check out the Footer component to see how it's done there. Keep in mind this is a boxed layout, meaning our content won't go edge to edge, the width limit for our containers is 1440px. 

![image](https://user-images.githubusercontent.com/3924990/59495652-a34a8100-8e44-11e9-8bed-13ce21bed8a6.png)

**Comment by tonynguyen111997** [comment]
This component is done. Closing issue.
