### ISSUE TITLE
Fix eslint errors

### ISSUE THREAD

**Issue by Andymendez100** [inland-empire-software-development/main#106]
**Components that require updating:** 
- all

**Tech to be used:** 
- ESLint 

**What is the current behavior:** Several errors are showing up because of formatting errors. 

**What is the new behavior:** Make sure all ESLint errors are addressed and that the compiler doesn't show linting errors. 

**Submission information [For PR]**:

All Submissions:
- The commit message follows our guidelines
- Testing steps have been added to this issue or the PR for this issue
- Submission has been tested in all supported browsers

New Feature Submissions:
- Code gone through a code review by at least one other person
- Code has been locally linted `yarn lint`

**Comment by lloan** [comment]
Closing - this has been addressed and fix pushed to master.
