### ISSUE TITLE
External links should be distinguishable from internal links

### ISSUE THREAD

**Issue by Andymendez100** [inland-empire-software-development/main#107]
**Components that require updating:** 
- Global script for all links

**Tech to be used:** 
- JS

**What is the current behavior:** As of right now, external links and internal links are not distinguishable. 

**What is the new behavior:**  All external links within the content should have an icon that lets the user know they will be going outside of the IESD network when hovered. Icon should only be visible when external link is hovered on. 

Example: 
![image](https://user-images.githubusercontent.com/3924990/68239010-148afc00-ffbf-11e9-98ff-129c09b8e0f4.png)

**Submission information [For PR]**:

All Submissions:
- The commit message follows our guidelines
- Testing steps have been added to this issue or the PR for this issue
- Submission has been tested in all supported browsers

New Feature Submissions:
- Code gone through a code review by at least one other person
- Code has been locally linted `yarn lint`

**Comment by lloan** [comment]
Thanks for opening this @Andymendez100 ! 

This one is up for grabs.

**Comment by lloan** [comment]
@erik-sandoval here is an example of what I'm talking about: https://www.esri.com/about/newsroom/press-coverage/ 

Go to the link above and hover over one of the cards 'read this article' link. You will see that the icon shows up on the right side. We can utilize the same icon. We can pull in the SVG and then apply it globally to all links who's `href` do not include `iesd.com` within them - those would be considered external links. This is only for links **within content**, not the navigation, as that would break the design.

**Comment by erik-sandoval** [comment]
on it!

**Comment by Andymendez100** [comment]
@erik-sandoval How is this issue coming along?

**Comment by lloan** [comment]
Closing because this is no longer needed.
