### ISSUE TITLE
Component: Footer

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#11]
Initial component to build other components off of.

This component shows you how to import images, use Calcite, interact with SASS files and structure your component file. 

File can be found here: `src/components/footer.js`

**Comment by tonynguyen111997** [comment]
https://i.imgur.com/PVBwmRn.png

Not a big issue, but the console is saying you used `class` instead of `className` for some of your elements.

**Comment by lloan** [comment]
Thanks @tonynguyen111997! Yep, that's one of the last components I added from a generator. I should have paid closer attention. Thanks!

**Comment by lloan** [comment]
@tonynguyen111997 thanks again for catching that, I caught a few other items as well, fixed those right up. Silly enough, i had nested ul tags within paragraph tags, that's been fixed. I've made the changes and merged in to dev branch.

**Comment by tonynguyen111997** [comment]
Great work on this, Lloan. Going to close this issue. Keep up the hard work!
