### ISSUE TITLE
Convert current speaker form to Google form

### ISSUE THREAD

**Issue by jenlatchman** [inland-empire-software-development/main#112]
Per Lloan, so that it can be added to the site

https://docs.google.com/document/d/1mSqbeNSfP83vv-tDY0ZMyM_aZmPrUvCJn2vJHxFUYGM/edit

**Comment by dsacosta** [comment]
@jenlatchman @lloan https://docs.google.com/forms/d/e/1FAIpQLSfXnBkkdrq5dfaRk_9y3kMp2CIgvpcVYVTrzsSSg-lKNaUd2g/viewform

**Comment by lloan** [comment]
Completed
