### ISSUE TITLE
Upgrade packages for project

### ISSUE THREAD

**Issue by Andymendez100** [inland-empire-software-development/main#114]
Components that require updating:
- package.json
- packages that need updating

Tech to be used:
- yarn

What is the current behavior: We are on an outdated version of next.js - this new version includes a lot of upgrades we can benefit from. All packages should be updated. 

What is the new behavior: We are on the latest version of next.js - all packages have been updated.

Submission information [For PR]:

All Submissions:
- [ ] The commit message follows our guidelines
- [ ] Testing steps have been added to this issue or the PR for this issue
- [ ] Submission has been tested in all supported browsers

New Feature Submissions:
- [ ] Code gone through a code review by at least one other person
- [ ] Regression testing has been done by at least one other person
- [ ] Code has been locally linted yarn lint

**Comment by lloan** [comment]
@Andymendez100 went ahead and groomed this - looks good now. Will go ahead and most likely work on this myself. I think I might want to start using Typescript so we all get more experience with that.

**Comment by lloan** [comment]
**Old version of packages:**
"@zeit/next-css": "^1.0.1",
"@zeit/next-sass": "^1.0.1",
"abortcontroller-polyfill": "^1.3.0",
"apollo-boost": "^0.4.4",
"axios": "^0.19.0",
"compass": "^0.1.1",
"dotenv": "^8.0.0",
"express": "^4.17.1",
"graphql": "^14.5.8",
"isomorphic-unfetch": "^3.0.0",
"lodash.debounce": "^4.0.8",
"moment": "^2.24.0",
"next": "^8.1.0",
"next-images": "^1.1.1",
"next-seo": "^1.11.2",
"node-fetch": "^2.6.0",
"node-sass": "^4.12.0",
"prop-types": "^15.7.2",
"react": "^16.8.6",
"react-apollo": "^3.1.2",
"react-dom": "^16.8.6",
"react-html-parser": "^2.0.2",
"sanitize-html": "^1.20.1",
"uikit": "^3.2.0"

**New version of packages:** 
"@zeit/next-css": "^1.0.1",
"@zeit/next-sass": "^1.0.1",
"abortcontroller-polyfill": "^1.4.0",
"apollo-boost": "^0.4.4",
"axios": "^0.19.0",
"compass": "^0.1.1",
"dotenv": "^8.2.0",
"express": "^4.17.1",
"graphql": "^14.5.8",
"isomorphic-unfetch": "^3.0.0",
"lodash.debounce": "^4.0.8",
"moment": "^2.24.0",
"next": "^9.1.3",
"next-images": "^1.2.0",
"next-seo": "^3.0.0",
"node-fetch": "^2.6.0",
"node-sass": "^4.13.0",
"prop-types": "^15.7.2",
"react": "^16.11.0",
"react-apollo": "^3.1.3",
"react-dom": "^16.11.0",
"react-html-parser": "^2.0.2",
"sanitize-html": "^1.20.1",
"uikit": "^3.2.3"


**Development dependencies - old:** 
"eslint": "^5.16.0",
"eslint-config-google": "^0.13.0",
"eslint-plugin-react": "^7.13.0", 
"jest": "^24.8.0",
"webpack": "^4.34.0"

**Development dependencies - new:** 
"eslint": "^6.6.0",
"eslint-config-google": "^0.14.0",
"eslint-plugin-react": "^7.16.0", 
"jest": "^24.9.0",
"webpack": "^4.41.2"

**Comment by lloan** [comment]
Couple of notes:

This required that I upgraded the node version on the VPS that hosts our sites. We also had to change the jenkins job (script) that is triggered when we update the branches on GitHub (master, staging, dev) - went ahead and added new scripts as well [development, staging, production].

**Comment by lloan** [comment]
Merged - dev -> staging -> prd
