### ISSUE TITLE
Mobile nav should close on menu item click

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/main#118]
**Components that require updating:**
- Nav

**Tech to be used:**
- React

**What is the current behavior:** 
On mobile screens, when you click a nav item it will scroll down to its destination, but the nav menu will still be open. This leads to bad UX, because the user is forced to click off the nav in order to close the nav.

**What is the new behavior:** 
On mobile, the nav should automatically close itself upon the user clicking a menu item that is not a dropdown item. 

Submission information [For PR]:

**All Submissions:**
- The commit message follows our guidelines
- Testing steps have been added to this issue or the PR for this issue
- Submission has been tested in all supported browsers

**New Feature Submissions:**
- Code gone through a code review by at least one other person
- Code has been locally linted using the command `yarn lint`

**Comment by abowler2** [comment]
Hey Tony ~ I'll work on this one.

**Comment by abowler2** [comment]
See submitted pull request for my solution to this issue: https://github.com/inland-empire-software-development/main/pull/120

**Comment by lloan** [comment]
Completed - thanks @abowler2 !
