### ISSUE TITLE
Component: Drag Component

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#12]
The drag component is essentially a component with a subtle animation that lets users know that the section it shows up in can be dragged left to right. This component does NOT need to be able to interact with the actual section it is used in. It just needs to render the asset and have a subtle pulse animation. This is the most basic implementation of this idea. @johnathantng and @kellytlam  have a few ideas, but for v1 we can use this. Down the road, as an enhancement, we can create a new issue and revisit this idea. 

This asset will have to be created with CSS. Sphere with a gradient, 2 arrows on left and right side. Arrows are NOT of the same width, outermost arrow on each side is heavier. You can search CSS examples to get inspiration on how to build this. Should be built using pure HTML/CSS.

Once a user interacts with the section where this component is rendered, it should disappear (fade out). 

Purpose of component is not to be used as a control but rather to inform the user that there is a dragging capability in the section it shows up on.

![image](https://user-images.githubusercontent.com/3924990/59496951-5ae09280-8e47-11e9-912d-d130f7e21856.png)

**Comment by ulisesgomez120** [comment]
Hello, I'd like to work on this.

**Comment by tonynguyen111997** [comment]
Hi @ulisesgomez120, unfortunately this component is already assigned to @VelazquezLuis. You'll have to discuss this with @VelazquezLuis.

**Comment by ulisesgomez120** [comment]
@tonynguyen111997 I'll reach out to him. In the meantime, is there anything else that I can help with?

**Comment by lloan** [comment]
@ulisesgomez120 if you're interested in working on something, we need a modal for the sponsorship component that @chrispierrelouis26 just finished. I'll be opening an issue shortly. This has been merged. Closing issue.

**Comment by ulisesgomez120** [comment]
Hello, spoke with Luis and he said it'd be okay if I worked on it.
