### ISSUE TITLE
Component: Goals

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#13]
This component is pretty simple. For v1, you can use 1 image for the left side. This image can be found here: `static/images/desktop/goals-section-gradient` - can provide the full asset without clipping if requested.

To get the padding required on both sides, Calcite uses 24 columns. You'll want your content to be within 20 columns and you can use pre-2 to move your content 2 columns from the left. Check out the Footer component to see how it's done there. Keep in mind this is a boxed layout, meaning our content won't go edge to edge, the width limit for our containers is 1440px.

![image](https://user-images.githubusercontent.com/3924990/59497625-acd5e800-8e48-11e9-9d94-7696ecfda7b4.png)

**Comment by johnathantng** [comment]
Component is complete and has been merged. Closing issue.
