### ISSUE TITLE
Add a way to reach our social medias

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/main#132]
**Components that require updating:**
- New component

**Tech to be used:**
- React

**What is the current behavior:**
Currently, when a user visits the IESD website there is no way for them to reach our social medias.

**What is the new behavior:**
Ideas:
- Add new menu items to the navbar that takes user to our social medias
- A side nav that contains just our social medias, like this:

![image](https://user-images.githubusercontent.com/36907562/69013146-b8ff2d80-0931-11ea-85e4-0de5b4a54f21.png)

**Submission information [For PR]:**

**All Submissions:**

- [ ] The commit message follows our guidelines
- [ ] Testing steps have been added to this issue or the PR for this issue
- [ ] Submission has been tested in all supported browsers

**New Feature Submissions:**
- [ ] Code gone through a code review by at least one other person
- [ ] Code has been locally linted using the command yarn lint

**Comment by tonynguyen111997** [comment]
@lloan Do you know if this is something we should allow the assignee to decide on how it should be implemented, or is there a specific way you want this done?

**Comment by lloan** [comment]
Closing because this is no longer needed. Redesign in on its way.
