### ISSUE TITLE
Update community images within API Dashboard

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#136]
**Components that require updating:**
- IESD API (wp-api from the dashboard -> api.iesd.com)

**Tech to be used:**
- WordPress
- GraphQL 

What is the current behavior: The current list of images are old.

What is the new behavior: We have our most recent images loaded in to the community component with all relevant information. 

**Instructions:** 

You need to get access to the API dashboard. This is what the community list currently looks like: 

![image](https://user-images.githubusercontent.com/3924990/69111189-a3712d00-0a31-11ea-9cc1-ae4c1fc29b64.png)

From this section, each item that you add will ask for the following information: 
- location
- description
- date of event 
- image for card 
- image modal 

![image](https://user-images.githubusercontent.com/3924990/69111379-4629ab80-0a32-11ea-89fd-f8cae3fd282e.png)

Submission information [**For PR**]:

**All Submissions:**

- [ ] The commit message follows our guidelines
- [ ] Testing steps have been added to this issue or the PR for this issue
- [ ] Submission has been tested in all supported browsers

New Feature Submissions:
- [ ] Code gone through a code review by at least one other person
- [ ] Code has been locally linted yarn lint

**Comment by VelazquezLuis** [comment]
I am still waiting for the images I saved in your hard drive for you to compress. I can try to do that if needed.

**Comment by lloan** [comment]
This was already completed - thanks @VelazquezLuis !
