### ISSUE TITLE
Archived Directory Page

### ISSUE THREAD

**Issue by chriscastaneda** [inland-empire-software-development/main#138]
Ideas to create a archived directory page for past events for members who could not attend to review in there spare time. 
Including: 
-Presentation/Live stream
-Materials needed
-Example of final product for reference

@lloan

**Comment by lloan** [comment]
@chriscastaneda this sounds like a great idea. Meetup.com offers a list of past events, but nothing at a glance like this. This requires a little planning and some design work. Let me think about how we can best set this up and i'll lay out some instructions on what the next steps are. 

Thanks!

**Comment by lloan** [comment]
Adding this concept to the new version of the application. Thanks!
