### ISSUE TITLE
Volunteers nav item is a dead link

### ISSUE THREAD

**Issue by abowler2** [inland-empire-software-development/main#139]
Under the Organization secondary menu the item for Volunteer does not have a path. Maybe it needs to be removed until that section is ready?

**Comment by VelazquezLuis** [comment]
I will clarify where we are at with that and proceed with the next steps thank you @abowler2 great catch

**Comment by VelazquezLuis** [comment]
issue has been dealt with accordingly, thank you @abowler2 keep them issues coming

**Comment by VelazquezLuis** [comment]
FIXED and merged in PULL #141
