### ISSUE TITLE
Component: Blog Post

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#16]
We need to create a blog post component that can be used to render blog posts from an API call. The API will return all the information required for each post: 
- image url
- category
- title
- author
- date published
- short description
- slug (used for identification)

You can initially create a grid of 4 columns and 2 rows of blog posts - these two rows will act as one section that will be draggable from left to right. This component does not require you to create the `drag` component, that's addressed in #12 but it does require that you make this section draggable. Check if something is being used to make things draggable yet or implement it yourself. 

![image](https://user-images.githubusercontent.com/3924990/59500166-bdd52800-8e4d-11e9-894f-a53e110bcbb4.png)

**Comment by rurru** [comment]
Interested in doing this one!

**Comment by tonynguyen111997** [comment]
Sounds good @rurru! I'll go ahead and assign this to you.

**Comment by dsacosta** [comment]
@rurru please update me on the status of this and also if you need any assistance.

**Comment by rurru** [comment]
@dsacosta Expecting to finish by the end of the weekend.  Have been stuck on converting the incoming JSON data into an array for display--once that's complete, the component will be finished shortly.

**Comment by dsacosta** [comment]
@rurru Thank you for the update!

**Comment by dsacosta** [comment]
@rurru Let me know if you need any assistance with converting the incoming JSON data.

**Comment by rurru** [comment]
@dsacosta Thanks for checking in--the data import/conversion turned out to be simple, so it's just down to making the component draggable and working out a CSS issue with the thumbnail image display.  I've posted details in the slack channel.

**Comment by lloan** [comment]
@rurru tried this out locally, this is what I see, wonder if your css is being overriden. 

![image](https://user-images.githubusercontent.com/3924990/61784299-53a19280-adbe-11e9-809a-4b4358f1c7b3.png)

**Comment by rurru** [comment]
@lloan Looks like it might be.  Should be easy to fix if that's the case--I'll check it out when I get home this afternoon.

**Comment by rurru** [comment]
@lloan Pretty sure I've figured out what's going on.  It has to do with having multiple swipers on one page--some of it is CSS conflicts, and some of it is the swiper object settings.  It looks like new swipers may inherit the properties of older ones if they aren't set in the new swiper.  Which would end up in some odd display results.  Tougher part will be tracking down those conflicts, but I should be able to do it by tomorrow evening.

**Comment by lloan** [comment]
Awesome job @rurru its working just fine on my end. Thanks! Merged - closing issue.
