### ISSUE TITLE
If no event scheduled, don't show HeroEvent component. 

### ISSUE THREAD

**Issue by VelazquezLuis** [inland-empire-software-development/main#163]
Components that require updating:

-  SingleEvent

Tech to be used:

    Next.js 

What is the current behavior:
Currently, when there's is no upcoming events nothing appears in the SingleEvent component on the website.

What is the new behavior:
If no upcoming events found, hide component.

image: 
![image](https://user-images.githubusercontent.com/35620778/71493617-f7bbb980-27f4-11ea-866c-75d5daaddddc.png)

All Submissions:

The commit message follows our guidelines
Testing steps have been added to this issue or the PR for this issue

    Submission has been tested in all supported browsers

New Feature Submissions:

Code gone through a code review by at least one other person
Code has been locally linted using the command yarn lint

**Comment by lloan** [comment]
I like that idea, that would be awesome. Thanks!

**Comment by VelazquezLuis** [comment]
need ideas on What action is taken when there's no upcoming events

**Comment by lloan** [comment]
Hiding the component (not rendering) seems like the appropriate action here. Great suggestion @VelazquezLuis  - thanks!

**Comment by VelazquezLuis** [comment]
Made Branch event-backup to work off of. and committed my initial solution. please review if correct or on the right path. thanks

**Comment by lloan** [comment]
Completed
