### ISSUE TITLE
Update colors for mentorship banner

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/main#166]
**Components that require updating:**
- Mentorship banner at the top of the website

![image](https://user-images.githubusercontent.com/36907562/71850653-aa0f3e80-3089-11ea-9fc8-838611b8bc39.png)

**Tech to be used:**
- React
- CSS
- SASS/SCSS

**What is the current behavior:**
Currently, the banner uses these colors:
- #F1AF21
- #EC2242
- #000000
- #FFFFFF (when link is highlighted)

These colors make the wording and links difficult to see when placed next to each other.

**What is the new behavior:**
- New colors that are easier to see when next to each other.

**Submission information [For PR]:**

**All Submissions:**
- [ ] The commit message follows our guidelines
- [ ] Testing steps have been added to this issue or the PR for this issue
- [ ] Submission has been tested in all supported browsers

**New Feature Submissions:**
 - [ ] Code gone through a code review by at least one other person
 - [ ] Code has been locally linted using the command yarn lint

**Comment by tonynguyen111997** [comment]
@lloan Do you know if we want to let the assignee decide the colors, or did you have a set of colors in mind?

**Comment by DonavonCai** [comment]
@tonynguyen111997 I'm going to try to work on this issue, I'll try to have it done by Monday, January 17.
