### ISSUE TITLE
Create a Blog page

### ISSUE THREAD

**Issue by hotRedPanda1** [inland-empire-software-development/main#168]
**Is your feature request related to a problem? Please describe.**
I like reading through blogs related to work-life in the tech industry. 
 
**Describe the solution you'd like**
(1) There should be various articles posted after a severe review and check to see that each article has met the specific guidelines of submission. 
(2) We need an article submission page that will allow writers to submit their article for review before it is posted. 

**Describe alternatives you've considered**
There must be a page of clear, concise article submission guidelines for writers to follow.

**Additional context**
(1) There must be a limit to how many articles are accepted and posted every month. 
(2) An article that meets the requirements yet cannot be posted for a specific month may or may not be recycled or saved and utilized in a later edition. 
(3) All articles that are considered for publication become the property of IESD or SPARK.

**Comment by lloan** [comment]
Transferred issue to main repository for www.iesd.com site.

**Comment by lloan** [comment]
Closing - The concept will be added to the new application.
