### ISSUE TITLE
Component: Sponsorship

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#17]
Omit the image on the left. This section requires the use of gradients. Gradient information comes from the `sass/base/colors.scss`. The classes `yellow-red` and `blue-green` are available for use. 

The buttons should be configured to log to console when clicked. The message logged to the console should be the title of the button. These will then be, in a separate tasks, be connected to a payment merchant. 

![image](https://user-images.githubusercontent.com/3924990/59500475-5c618900-8e4e-11e9-9001-9e644a833fd3.png)

**Comment by chrispierrelouis26** [comment]
Interested in working on this component.

**Comment by dsacosta** [comment]
@chrispierrelouis26 please update me on the status of this issue and also if you need any assistance.

**Comment by chrispierrelouis26** [comment]
Good morning david , I have a few things I need to change on my component style wise and then I should be complete. I have a phone interview Tuesday so Iv been studying for that . I will have my component complete this weekend.

**Comment by dsacosta** [comment]
@chrispierrelouis26 Thank you for the update!

**Comment by lloan** [comment]
@chrispierrelouis26 Hey Chris! Can I start testing this one? Let me know boss!

**Comment by chrispierrelouis26** [comment]
Hey lloan ! The only issues i'm currently having is with media queries for the mobile view. I meant to ask about it at the meet up but i got carried away!

**Comment by lloan** [comment]
@chrispierrelouis26 still having issues with media queries?

**Comment by chrispierrelouis26** [comment]
Yes, I still cant seem to get my buttons to stack along side each other
when i add my media queries

**Comment by lloan** [comment]
Oh okay, when you get a second, push whatever you have and I can take a look.

**Comment by chrispierrelouis26** [comment]
Just pushed

**Comment by lloan** [comment]
@chrispierrelouis26 awesome job! Thanks for working on this.
