### ISSUE TITLE
Text bleeds out of hero event

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/main#175]
**Components that require updating:**

- Hero Event (SingleEvent.js)

**Tech to be used:**

- CSS
- React

**What is the current behavior:**
Font bleeds out of container because event title is too long.

![image](https://user-images.githubusercontent.com/36907562/77242078-f7467b00-6bb7-11ea-87f3-8e609c6b5560.png)

**What is the new behavior:**
Ideas:

- Lower font-size when text is certain length.

**Submission information [For PR]:**

**All Submissions:**

- [ ] The commit message follows our guidelines
- [ ] Testing steps have been added to this issue or the PR for this issue
- [ ] Submission has been tested in all supported browsers

**New Feature Submissions:**

 - [ ] Code gone through a code review by at least one other person
 - [ ] Code has been locally linted using the command yarn lint

**Comment by ldaws003** [comment]
Hi, I'll fix it.

**Comment by lloan** [comment]
Thanks!

**Comment by lloan** [comment]
Closing as #182 will take care of this.
