### ISSUE TITLE
Overflow of Newsroom events on mobile 

### ISSUE THREAD

**Issue by ldaws003** [inland-empire-software-development/main#177]
**Components that require updating:**

- Blog.js

**Tech to be used:**

- CSS 
- React

**What is the current behavior:**
The Newsroom section causes the front page to not fit on mobile.

![0D76C116-3D46-4E36-AD19-E64A5D5A59AA](https://user-images.githubusercontent.com/41959451/77834321-1afe4980-7101-11ea-8f1f-57b92401f8d9.png)
![FEB6C6C5-1F7F-46C9-B809-7FCD8C9194BA](https://user-images.githubusercontent.com/41959451/77834323-1f2a6700-7101-11ea-947e-f29438754968.png)

**What is the new behavior:**
Ideas:

- Change the overflow property of the ul on mobile to remove the overflow

**Comment by HeyItsFelipe** [comment]
Hello @ldaws003 !  I'm unable to replicate.  Can you specify device or browser width?

**Comment by ldaws003** [comment]
Hi @HeyItsFelipe . It's on an iphone. It's done by scrolling on the screen while not touching the newsroom itself.

**Comment by lloan** [comment]
Closing because of the redesign. However, a new issue has been opened to look into this, thank you for reporting this!
