### ISSUE TITLE
Component: Sponsors

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#18]
This component has a light background that can be found within the `static` folder. There should be 4 columns for each row. There can initially be 1 row, the second row in the image is for informational purposes. Each column should be responsive and equal in width to the other columns - Calcite allows for this quite easily. Search in the documentation under Grid > Groups 

![image](https://user-images.githubusercontent.com/3924990/59501054-8ebfb600-8e4f-11e9-8028-ba82b676d809.png)

**Comment by usrbom** [comment]
I would like to try this. Is this to be added below the Events Section?

**Comment by tonynguyen111997** [comment]
Hi @usrbom , I believe @elyselam is currently working on this component already. You'll have to talk to her about this component.

**Comment by usrbom** [comment]
Oh It's alright, I will pick up something else.

**Comment by elyselam** [comment]
@lloan in terms of the images, do i keep those the same?

**Comment by lloan** [comment]
@elyselam yes, leave those as placeholders.

**Comment by johnathantng** [comment]
I believe this component has been merged to dev - closing this issue.
