### ISSUE TITLE
Update mission statement and related sections

### ISSUE THREAD

**Issue by HeyItsFelipe** [inland-empire-software-development/main#185]
-Replace current mission statement in Our Mission with **Building Communities around Technology**
-Replace About Us section with Our Mission section, but keep About Us text safe as we might need it for later
-Remove the two sections below it, but keep Our Goal text safe as we might need it for later
It should look like this:

![Screen Shot 2020-07-02 at 7 40 31 PM](https://user-images.githubusercontent.com/12819928/86426207-ebc91c80-bc9b-11ea-9dbe-9df7ee256f3c.png)

But style it better, like make it centered and stuff.
Also update nav as sections will be moved.

**Comment by VelazquezLuis** [comment]
PR has been merged will close issue
