### ISSUE TITLE
Component: Community 

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#20]
This component has a light background, image can be found within `static`

Images can vary in size, as long as they're not bigger than 80% the height of the component. The spacing between each image will be the same, make sure to check out the spec sheet. This section needs to be draggable from left to right, etc. Don't worry about the drag element, that is addressed in #12 

Images can come from an array OR you can get creative. For v1, images from an array are fine, we can manually put those in for now. In the future, we could make it where there is a folder where when we drop images, they show up in this component, sorted by date last modified, making the latest image show up first. 

![image](https://user-images.githubusercontent.com/3924990/59502836-adc04700-8e53-11e9-8527-1b38697aa9a9.png)

**Comment by dsacosta** [comment]
@lloan let me know if you need me to assign this to someone that has expressed interest in helping but has not been assigned any work.

**Comment by lloan** [comment]
Merged
