### ISSUE TITLE
Component: Join

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#22]
Simple component with a background and big button in the center. Button links to the meetup.com page for IESD to join us there - should open a new tab. We don't want to take the user away from the site or lose their place on the site. Image can be found under the `static` folder. 

![image](https://user-images.githubusercontent.com/3924990/59504227-5a4ff800-8e57-11e9-8e0b-3988cd83e814.png)

**Comment by tonynguyen111997** [comment]
Great work on this component, Kelly. Since this component is done, I'm going to go ahead and close this issue.
