### ISSUE TITLE
Component: leadership

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#23]
This component will be redesigned in the future, for now, this is our v1 for go-live.

This component will have two rows, one of organizers/contributors/etc and another for speakers that have given talks at IESD. The drag element will be addressed here: #12 - users will be pulled from an array of objects. Each object will have the user name, title and image. One array for speakers and another for organizers. 

You can use a placeholder image @tonynguyen111997 can we add 1-2 images from those used on Ledkyb? Thanks! 

Make sure to checkout the specs sheet

![image](https://user-images.githubusercontent.com/3924990/59505198-997f4880-8e59-11e9-98e5-75c9429f3367.png)

**Comment by dsacosta** [comment]
@amacbain1 let me know the status of this issue and also if you need any assistane.

**Comment by amacbain1** [comment]
Sorry for my poor response time @dsacosta. I think it's pretty much finished. .

**Comment by dsacosta** [comment]
@amacbain1 no worries, thank you for the update!

**Comment by lloan** [comment]
Merged
