### ISSUE TITLE
Component: Hero Section

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/main#29]
This component **DOES NOT** include the navigation, side bars and event section. For the navigation, side bars and event section, just leave a placeholder comment.

This component only needs the background image that can be found at `static/images/desktop`. 

![image](https://user-images.githubusercontent.com/36907562/59729769-ce422580-91f4-11e9-9d4d-a635cd70b657.png)

For mobile devices:

![image](https://user-images.githubusercontent.com/36907562/59730883-e0be5e00-91f8-11e9-83a9-ae1348be9521.png)

**Comment by dhuan008** [comment]
I'm interested in working on this!

**Comment by tonynguyen111997** [comment]
This component is finished. Great work David!
