### ISSUE TITLE
Gather Success Stories information

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/main#31]
Need to collect information for success stories. 

I created a file called `successStoriesData.js` that will be a part of the PR for issue #19 Component: Success Stories. The file has a JavaScript object that contains the following properties:

- imageURL (600x650 width x height)
- name
- title
- excerpt
- linkToStory

![image](https://user-images.githubusercontent.com/36907562/59839262-3718c300-9305-11e9-87a0-7b55a53d6d55.png)

**Comment by tonynguyen111997** [comment]
Felipe's and Amy's stories have been added.

**Comment by lloan** [comment]
In the future, we can create an issue to ADD success stories in the https://github.com/inland-empire-software-development/wp-api repository. Closing this down as the component is on its second iteration, has been deployed and success stories have been added.
