### ISSUE TITLE
Blog Post Backend API

### ISSUE THREAD

**Issue by rurru** [inland-empire-software-development/main#33]
Backend blog functionality needs to be implemented with an API that can be used to access and display blog posts.  Post information that should be made available to the frontend component is listed in [#16](https://github.com/inland-empire-software-development/main/issues/16), which requires this item for completion.

**Comment by lloan** [comment]
@rurru 

Can you please try the url: https://blog.ie-sd.com/wp-json/wp/v2/posts 

We should take a look at what data we need to create the blog components (articles that get rendered) so we can extend the API to serve that.

**Comment by rurru** [comment]
Sure thing--the data comes up easily enough,and it looks like most of the
data we need is already baked into the api (
https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/%24post_ID/).
I can hook up what I've written so far to grab the sample data and see how
it looks, which should give a better idea of any extensions that might be
needed as well.

**Comment by lloan** [comment]
@rurru Is there anything else we need to do for this issue? Do I need to add new fields? Thanks!

**Comment by rurru** [comment]
Nope, not unless there are any other fields we need to support for future versions.  The API as is provides all the information specified in the blog post component.

**Comment by tonynguyen111997** [comment]
Since the current API currently provides all the information needed, should we go ahead and close this issue?

**Comment by lloan** [comment]
@tonynguyen111997 makes sense. I'll go ahead and close it.
