### ISSUE TITLE
Component: Error Boundaries

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/main#35]
Create Error Boundary class components that will provide components that make API requests a fallback UI. 

It would be nice to have the ErrorBoundary component accept a prop that lets you display a custom error message. Such as `<ErrorBoundary message={'Something went wrong'} />`

You can read up more about this at https://reactjs.org/docs/error-boundaries.html

This can be added after version 1.0

**Comment by dsacosta** [comment]
@mlatini Hi Matthew, please update me on this issue and let me know if you need any help.

**Comment by mlatini** [comment]
I tried to implement error boundaries but was running into some nonsensical challenges. I finally discovered that it's related to server side rendering, which isn't supported by Error Boundaries. 

It seems that the options are manually putting a try/catch into every render() method or using babel-plugin-try-catch-wrapper to automate the process. 

I'm open to suggestions. 

https://github.com/zeit/next.js/issues/4262

**Comment by dsacosta** [comment]
@VelazquezLuis Hey Luis, do you have any suggestions for Matthew?

**Comment by VelazquezLuis** [comment]
Hi @mlatini  Are you still having issues?  Error Boundary classes can be tricky. on which branch are you working on? I would like to see the code and see to whom I can resolve this with.

**Comment by mlatini** [comment]
Hi @VelazquezLuis. Sorry for the delay. My hard drive crashed on my laptop and I was down for a couple days while I restored from backup. I did lose a couple of things including error boundaries code. I can re-write it but from, everything I've read, error boundaries won't work with SSR. I, _believe_, we're using SSR?

**Comment by VelazquezLuis** [comment]
sorry to hear that. I'm positive we are since we are using next.js (https://nextjs.org/features/server-side-rendering). I will investigate further

**Comment by lloan** [comment]
@VelazquezLuis @tonynguyen111997 Can we revisit this? What is the use for this?

**Comment by tonynguyen111997** [comment]
This would just be for error handling. The use for this would be for when the API fails, we can have our components gracefully fail. That way when the API isn't working, some sort of feedback can be displayed, rather than nothing appearing or the website crashing.

**Comment by lloan** [comment]
@tonynguyen111997 at the moment, if we don't get anything back, we display a piece of text that says we were unable to provide them with the requested data. Perhaps we can convert that in to a component that takes in text we want to provide. That component can be styled and reused. So that users know that when they see that, its an API failure, etc. Is this what we're trying to do pretty much?

**Comment by lloan** [comment]
Let's make sure we address error handling in sponsors component and all components alike (that issue was closed)

**Comment by lloan** [comment]
Closing because this is no longer needed.
