### ISSUE TITLE
Loading indicator component for API calls

### ISSUE THREAD

**Issue by johnathantng** [inland-empire-software-development/main#48]
This issue does **NOT INCLUDE** implementing the LoadingIndicator component. Only the creation of the component. 

EDIT: This component will be used for the events API

If the user has slow internet speeds, it is important to provide them with feedback that tells them that the site is currently retrieving information to be displayed.

Calcite does provide a loading indicator in `main/sass/vendors/calcite/img/loader-ie9.gif`, but I'm unsure about how this specific loading indicator would translate on the design of the site. You may have to take some initiative in regards to creativity.

Here's an example of what I am referring to:
![loading](https://user-images.githubusercontent.com/47069326/61094662-f3e1d980-a404-11e9-9c5c-76ff9cd48a49.gif)

Here's the article you can refer to - Just remember that only the component has to be made: https://www.basefactor.com/react-how-to-display-a-loading-indicator-on-fetch-calls

**Comment by mlatini** [comment]
I’d like to work on this if possible. Can I just assign it to myself?

**Comment by lloan** [comment]
@johnathantng - I'm assuming this is going to be built for the use of the events API loading? 
@mlatini - should be fine, I don't think anyone is assigned to this yet.

**Comment by johnathantng** [comment]
@lloan Yes, this will be for the events API.

**Comment by mlatini** [comment]
Is there going to be an issue for the implementation as well or is someone already working on that? I browsed the issues and didn’t see anything but I may have missed it. I would be interested in working on the implementation as well if possible.

**Comment by dsacosta** [comment]
@mlatini Please let me know the status of this project and let me know if you need any help.

**Comment by mlatini** [comment]
I have a working component, at least ready for an initial review, but had a hard drive crash yesterday. Recovering from backup so I'll push what I have once that's done.

**Comment by mlatini** [comment]
Created branch loadingIndicatorMatthew off dev branch and pushed to remote. 

The loading indicator is working based off main/sass/vendors/calcite/img/loader-ie9.gif, which I moved to static/images/loader-ie9.gif 

Created a few components for testing, which are listed in the commit and which I will remove before PR. 

Added LoadingIndicator component to pages/index.js for testing, which will be removed before PR. 

If the look is fine I can remove the testing components and submit for PR.

**Comment by dsacosta** [comment]
@VelazquezLuis Can you review this?

**Comment by VelazquezLuis** [comment]
Thank you will take a look.

**Comment by johnathantng** [comment]
Component has been merged to dev - closing this issue.

**Comment by lloan** [comment]
@johnathantng any way you can recover this from the old version and incorporate in to the new version of the site?

**Comment by lloan** [comment]
Handled by #135 - new Loader component.
