### ISSUE TITLE
Component: Navigation

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#5]
Component involves creating the navigation for the hero section. This will require you test mobile responsiveness AND creating the mobile version of the menu. Its a bit more involved than other components. You will utilize a lot of custom CSS and some JavaScript. We don't have a 'on scroll' state for the desktop navigation, but that can be part of v2 enhancements. For now, the focus is on getting a v1 ready for go-live.

**Comment by tonynguyen111997** [comment]
The initial navbar component has been merged into dev, and is considered "done" for our MVP. Navbar enhancements are currently being worked on in issue #41.

Going to close this issue. Reopen if you think it shouldn't be closed.
