### ISSUE TITLE
Violation due to non-passive event listener

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/main#50]
Not sure if this is an issue that needs to be resolved or if it can be resolved. When you open the console log it says there are 25 violations.

![image](https://user-images.githubusercontent.com/36907562/61166001-7b4e4c00-a4dc-11e9-801d-877e5ea473bc.png)

If you remove the google map from the footer

![image](https://user-images.githubusercontent.com/36907562/61165975-58239c80-a4dc-11e9-907b-19f7bdfcf4ba.png)

the violations go away

![image](https://user-images.githubusercontent.com/36907562/61166011-928d3980-a4dc-11e9-88f3-8e3c0e744972.png)

**Comment by ulisesgomez120** [comment]
@tonynguyen111997 I looked around and read that you can get around it by unchecking Use Touch Events in you dev tools.

**Comment by lloan** [comment]
@tonynguyen111997 is this still an issue? What is the benefit we gain from fixing this if its a verbose warning from the console? Should we only address real warnings and errors or also verbose warnings?

**Comment by VelazquezLuis** [comment]
I Like the map but a Picture of the entrance Is a Great thing to add

**Comment by tonynguyen111997** [comment]
I like the map as well, and I agree that a picture of the entrance may be helpful. Not sure where it would fit in our current design, but if we can add a picture that would be great. This issue can be closed, as it doesn't look like it's appearing anymore. Plus, I guess there isn't really a benefit from fixing it, since it's just a warning. 

@lloan If it's fine with you, I'm going to close this issue.

**Comment by VelazquezLuis** [comment]
NO issue found close it @tonynguyen111997
