### ISSUE TITLE
Component: Social Media Floating Bar (right)

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#6]
This component can be found on the hero component, it will float on the right hand side of the website. That means the position for this component is fixed on the screen and should align with the Contact Floating Bar (left). If you take this component, you **should** take that component as well. The icons found in this component can be pulled from FontAwesome - which our project is already using. 

![image](https://user-images.githubusercontent.com/3924990/59491114-27980680-8e3b-11e9-8d49-da6890c055c5.png)

**Comment by dsacosta** [comment]
@yzhan407 Please update me on this issue and let me know if you need help.

**Comment by yzhan407** [comment]
> @yzhan407 Please update me on this issue and let me know if you need help.

Hi
this one is the same as the left floating bar. I made a PR about those two components.  In other words, if there is no problem with that PR, this one is also finshed.

**Comment by johnathantng** [comment]
Component has been merged - closing this issue.
