### ISSUE TITLE
Component: Contact Floating Bar (left)

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#7]
This component is almost identical to #6 

This component will require that you create a fix component that floats on the left hand side of the desktop version of the site. Icons can be pulled from FontAwesome, which our project is currently using. The phone icon should be linking to the phone number found in the footer, the email icon should open an email client pointing to the email found in the footer and the message bubble should open a contact form. That contact form will be a separate component. In the meantime, you can make it so that when you click on the button a function is fire that prints a message to the console "placeholder contact button". 

![image](https://user-images.githubusercontent.com/3924990/59491500-bc026900-8e3b-11e9-9466-0a3ba42ed532.png)

**Comment by dsacosta** [comment]
@yzhan407 let me know the status of this issue and if you need any help.

**Comment by yzhan407** [comment]
> @yzhan407 let me know the status of this issue and if you need any help.

Hi. I have pushed a new branch and the only thing left is to make a pull request. I am having a little bit of problem with making a PR. I will figure that out soon.

**Comment by dsacosta** [comment]
@yzhan407 Thank you for the update!

**Comment by dsacosta** [comment]
@yzhan407 Hi Yifan. Did you figure out how to make the PR? Let me know if you need any help.

**Comment by yzhan407** [comment]
> @yzhan407 Hi Yifan. Did you figure out how to make the PR? Let me know if you need any help.

Hi,
  I made a PR last week, and two days ago I got the review. I just made a new PR today hopefully this one will satisfy all the requirements.

**Comment by johnathantng** [comment]
Component has been merged - closing this issue.
