### ISSUE TITLE
Improve performance of website

### ISSUE THREAD

**Issue by tonynguyen111997** [inland-empire-software-development/main#72]
As of July 27th the performance score (according to Google's Lighthouse tool) is a 20 out of 100. I'm sure that as we continue to add more content to the website it will continue to get slower. 

![image](https://user-images.githubusercontent.com/36907562/61997195-f83c0280-b052-11e9-9fd0-4464770346c8.png)

Things to consider:
- Lazy loading for images that are offscreen. 
- Make sure images are properly sized

The lighthouse tool also suggests other ways we can improve the performance.

We can break this issue into smaller issues, such as an issue for implementing lazy loading.

**Comment by sstylianides** [comment]
hi @tonynguyen111997 . I just did the lighthouse test and I think I can handle a lot of these performance issues.  Can you assign this issue to me?

**Comment by lloan** [comment]
@sstylianides can you, for the sake of documentation, please list the items you'd be working on? That way I can add or prioritize. A big part of the effort will be optimizing these images (600k to 15k, example). Converting images that SHOULD be jpgs from pngs. If you have Photoshop, you can set the res to something like 60 on a JPG and it should still be decent.

**Comment by sstylianides** [comment]
@lloan I can definitely do the picture conversions... there is also a few other things that the lighthouse test pointed out that I can do.

1. Remove Unused CSS
2. The page does not contain a heading, skip link, or landmark region 
3. Document doesn't have a <title> element 
4. <frame> or <iframe> elements do not have a title
5. Image elements do not have [alt] attributes 
6. Internationalization and localization

Let me know if this list is a good and I'll get it started.

**Comment by lloan** [comment]
@tonynguyen111997  @sstylianides  is this still active? Can we take a look at the new version, create a new list and then figure out who will work on it? Thanks! 

@dsacosta

**Comment by lloan** [comment]
@tonynguyen111997 once you get the overarching list of what needs to be done, break it out in to smaller actionable tasks using the template we're using for newer tasks. We need to make sure these issues are organized so that new contributors have an easier time jumping in. 

Thanks!

**Comment by blueocto** [comment]
Hey all, I'd love to help with this, have forked and followed your docs, however, when running `yarn dev` it's giving me an error. (see attached)
[consolelog.txt](https://github.com/inland-empire-software-development/main/files/4584112/consolelog.txt)

**Comment by lloan** [comment]
Hi @blueocto, it looks like we're going to be rebuilding this application. We have a new issue and will be updating it shortly. We will be posting more issues that are going to be up for grabs and would love the help. Thanks a ton!
