### ISSUE TITLE
Component: Modal

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#76]
We need a modal component to open up on the screen for different purposes. It can be fixed, dead center and only take up the space required by the contents within it. We also need to make sure that whatever we drop in, like an iframe or any content is also centered. 

Example use case: We will be using this for the sponsorship component - we will be dropping in an iframe for donation payments via WePay.  

Notes: Ideally, you can wrap whatever content goes in to the modal in a div with a class that will make sure its all centered within the modal. 

During development, you can use this iframe to fill the modal:

```
<iframe frameborder = "0" height="1100" scrolling="no"  src = "https://give.donatekindly.org/ie544/makedonation/donation/c711001e-0442-4c13-adeb-feb07e121807"  width="560" ></iframe>
```

**Desktop**
![modal-desktop](https://user-images.githubusercontent.com/3924990/62820052-46510b80-bb13-11e9-9f40-978ed3e1b8fd.jpg)

**Mobile**
![modal-mobile](https://user-images.githubusercontent.com/3924990/62820053-46510b80-bb13-11e9-9b35-6a306cc31fee.jpg)

**Comment by ulisesgomez120** [comment]
I'd like to work on this

**Comment by lloan** [comment]
Closing this task. New version of site now has modal component. But we have several places that need to implement the new version of the modal. Donation section included, which didn't make it part to the latest release of the site.

**Comment by ulisesgomez120** [comment]
Hey Lloan,

Yea I'd love to work on implementing some of those. I'll check out the open
issues.
