### ISSUE TITLE
Component: Hero Section Event 

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#8]
This component has a couple of steps. 

First, you need to create the actual component, so that you can pass in the data once you have it. 
Second, you need to make an API call to Meetup.com to get the latest event. So which event is coming up soon? That's the event you need to get. You need the following data points:
- Date
- Time 
- Title 
- URL for event on Meetup.com (for button to link to)

For now, we can omit the 'Presented By' line of text as we don't have a custom implementation or connector between Meetup.com and our own event management system. That will be an enhancement down the line. 

![image](https://user-images.githubusercontent.com/3924990/59492246-6dee6500-8e3d-11e9-851b-705bd0a6e1b8.png)

**Comment by johnathantng** [comment]
This component has been created. Let's close this issue.

**Comment by lloan** [comment]
@johnathantng  Can we make sure this looks good on mobile? Does it look like this on your end? Only thing it needs is some space at the bottom - between the black section (slogan) and the button.

![image](https://user-images.githubusercontent.com/3924990/61358936-3efa5300-a830-11e9-9b36-11620ab4ff41.png)

**Comment by tonynguyen111997** [comment]
Looks like some issues were fixed in PR #57 . I'm going to go ahead and close this. Reopen if needed.
