### ISSUE TITLE
404 loads on some pictures and http request over https throws console error. 

### ISSUE THREAD

**Issue by erik-sandoval** [inland-empire-software-development/main#81]
When the site loads it throws this console error.

![Screen Shot 2019-08-28 at 10 19 02 AM](https://user-images.githubusercontent.com/48698089/63878349-4871f180-c97e-11e9-9161-488974811c3a.png)

**Comment by lloan** [comment]
@erik-sandoval can you check and verify this issue? If its no longer occuring, can you go ahead and close the issue? We just launched v2 of the site, want to make sure this was addressed. Thanks!

**Comment by lloan** [comment]
Closing out. Received confirmation via Slack that this is no longer occurring. Thanks @erik-sandoval
