### ISSUE TITLE
Connection is not secure- site info

### ISSUE THREAD

**Issue by VelazquezLuis** [inland-empire-software-development/main#82]
the site info the the top left where the lock is located is not green. Says parts of site is not secure, such as images.  I found this https://stackoverflow.com/questions/34273230/firefox-some-parts-of-this-page-are-not-secure-such-as-images-what-counts-a and we might have issues either regarding maps or some other external image we are referencing  without the https at the beginning.   

![image](https://user-images.githubusercontent.com/35620778/63878724-09906b80-c97f-11e9-889c-7c91b59b1306.png)

**Comment by lloan** [comment]
@VelazquezLuis @tonynguyen111997 @Andymendez100 @dhuan008 @dsacosta @JasonEb 

Is this still an issue, can someone verify this?

**Comment by tonynguyen111997** [comment]
The website is showing up as secure for me on both Chrome and Internet Explorer. If we can get one more person to verify, I think it's safe to close this issue.

**Comment by VelazquezLuis** [comment]
Yeah it's fine now will close.
