### ISSUE TITLE
add new crew member to our websites EG david acosta

### ISSUE THREAD

**Issue by VelazquezLuis** [inland-empire-software-development/main#87]
**Components that require updating:** 
- operations

**Tech to be used:** 
- wp-api (api.iesd.com)

**What is the current behavior:** David Acosta, Project Manager, is missing from the operations team list. 

**What is the new behavior:** David Acosta should show up on the operations list.

**Submission information [For PR]**:

All Submissions:
- The commit message follows our guidelines
- Testing steps have been added to this issue or the PR for this issue
- Submission has been tested in all supported browsers

New Feature Submissions:
- Code gone through a code review by at least one other person
- Code has been locally linted `yarn lint`

**Comment by tonynguyen111997** [comment]
Great issue, Luis. I can do that if nobody is planning to.

**Comment by lloan** [comment]
@VelazquezLuis @tonynguyen111997 can we check in with @dsacosta and see if this is still a valid issue?

**Comment by tonynguyen111997** [comment]
@lloan Yea I think this is still a valid issue. I've been lagging on getting everyone's picture for this issue.

**Comment by lloan** [comment]
No longer a valid issue as David has stepped back for a while.
