### ISSUE TITLE
Component: Slogan 

### ISSUE THREAD

**Issue by lloan** [inland-empire-software-development/main#9]
Great component for new contributors to work on or get experience with the workflow for this project. This component is essentially a whole section with a custom background. Initially, it was considered to make 'Community and Developer Excellence' to be set as text, but for the sake of simplicity and getting v1 out the door, let's use the image with the text embedded. Make sure the height of the component matches the design provided. The overall layout is boxed, meaning, this is not a full-width component. Look at other existing components to see how to get this started. 

Background: (./static/images/desktop/developer-and-community-excellence.jpg)

![image](https://user-images.githubusercontent.com/3924990/59492378-b3129700-8e3d-11e9-861a-691cc018f7cc.png)

**Comment by tonynguyen111997** [comment]
Changes have been merged into dev. I'm going to go ahead and close this issue. Great work @kellytlam!
