### ISSUE TITLE
Slider component is not intuitive - users don't know to swipe or slide

### ISSUE THREAD

**Issue by Andymendez100** [inland-empire-software-development/main#95]
**Components that require updating:** 
- speakers
- operations
- community
- success stories

**Tech to be used:** 
- React

**What is the current behavior:** Sliders are currently not intuitive. Users don't know if they can slide left or right. We currently have some text that talks about being able to slide, but we can do better.

![image](https://user-images.githubusercontent.com/3924990/68253599-2a0f1e80-ffdd-11e9-9a1e-d8700b07aaf6.png)

**What is the new behavior:**  Sliders should have some form of way to show users they can slide. Something like what we are doing for the blog component on mobile, see example: 

![image](https://user-images.githubusercontent.com/3924990/68253565-11066d80-ffdd-11e9-8945-4eda220c1f10.png)

We can have each component have its own position component for the slider, so users know how the sliders work. 

**Submission information [For PR]**:

All Submissions:
- The commit message follows our guidelines
- Testing steps have been added to this issue or the PR for this issue
- Submission has been tested in all supported browsers

New Feature Submissions:
- Code gone through a code review by at least one other person
- Code has been locally linted `yarn lint`

**Comment by tonynguyen111997** [comment]
Issue is up for grabs

**Comment by VelazquezLuis** [comment]
will see what I can do. 
@lloan  is it safe to assume we branch off master?

**Comment by lloan** [comment]
Yes, thatd be the way to go

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lloan** [comment]
@VelazquezLuis looks great so far!

Just a few notes from what I saw:

Let's add some spacing at the bottom of the speakers component, below the slider. I'd say have it push the the success stories component up to the red line below: 

![image](https://user-images.githubusercontent.com/3924990/68599942-6536a500-0456-11ea-84f8-71feb1085ff0.png)

For the success stories component, let's make sure that the circles are outside of the black background. We want to make sure that the image goes from top to bottom and doesn't just leave an odd space at the bottom. Perhaps we could do something like this? 

![image](https://user-images.githubusercontent.com/3924990/68600297-1ccbb700-0457-11ea-9ea7-690fe7f4aada.png)

Thanks!

**Comment by VelazquezLuis** [comment]
Ready to be reviewed once more. Fixed changes from above.
also need input, if ccs changes on _story.scss were made correctly.

**Comment by lloan** [comment]
Thanks @VelazquezLuis  - PR has been merged.
